### ISSUE TITLE
Aborter does not abort uploads that are in timeout / retrying

### ISSUE THREAD

**Issue by Garbanas** [Azure/azure-storage-js#76] opened 2019-03-01 15:21 UTC
### Which service(blob, file, queue, table) does this issue concern?
Uploads in browser with `uploadBrowserDataToBlockBlob()`

### Which version of the SDK was used?
10.3.0

### What's the Node.js/Browser version?
Chrome Browser v72.0.3626.119

### What problem was encountered?
When using an Aborter to abort pending uploads and the upload is currently in timeout / retry loop because of connection problems (or similar issues), the upload is later resumed although the `Aborter.aborted` returns `true`.

### Steps to reproduce the issue?
1. Upload a large file to blob storage with `uploadBrowserDataToBlockBlob()` and an Aborter, so you have time to cancel the upload and the chunk upload is used. `Aborter.none` should suffice; no timeout is specified.
2. During upload go offline. This can be achieved through your browsers' developer tools network tab.
3. Cancel the upload process by calling `aborter.abort()`.
4. Go online again.
5. View the network tab of your browser to see the upload resuming.

### Have you found a mitigation/solution?
This is just an assumption and has not yet been tested / verified:
`BlockBlob.stageBlock` => `StorageClientContext.sendOperationRequest()` could check early for `abortSignal.aborted` and raise an error to fail the returned Promise.
Also in `Batch.addOperation()` the `this.state === BatchStates.Error` should be checked early _before_ `await operation();` is called.

**Comment by XiaoningLiu** [comment] 2019-03-04 02:18
Hi @Garbanas 

Thanks for pointing this out and the mitigation plan proposed! This is a bug while the abort event doesn't get handled during the waiting time between 2 retries.

The root cause is in `RetryPolicy` here:

https://github.com/Azure/azure-storage-js/blob/e084d30146555365ee1d3c4d84c1888d8e0db01f/blob/lib/policies/RetryPolicy.ts#L347

The delay method should handle the abort event, and abort the delay immediate.

**Comment by XiaoningLiu** [comment] 2019-08-02 08:56
This is fixed in 10.4.0, see https://www.npmjs.com/package/@azure/storage-blob

**Closed** 2019-08-02 14:27 UTC
Labels: bug
